# Python Basics

In [1]:
print(2+2)
print((50-5*6)/4)
print((3*4)+2)

4
5.0
14


In [2]:
x=3
y=4
print(x*y)

12


In [3]:
print("Hello"+"Python")
str1 = "Hello"
str2 = "Python"
str3 = str1 + str2
print(str3)

HelloPython
HelloPython


In [4]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
scope = [1,2,3,4,5]
for x in scope:
    print(x)

1
2
3
4
5


In [6]:
scope = [1,2,3,4,5]
for x in scope:
    print(x)
    if x<3: # 3보다 작으면 계속 진행하고 아니면 멈춤
        continue
    else:
        break

1
2
3


In [7]:
for i in range(0,10,2): # 0부터 9까지 간격 2씩
    print(i)

0
2
4
6
8


In [8]:
for i in range(2,12,3): # 2부터 11까지 간격 3씩
    print(i)

2
5
8
11


In [9]:
for i in range(0,10):
    if i%2==0: # 짝수면 출력
        print(i)

0
2
4
6
8


In [10]:
for i in range(0,5):
    if i%3==0:   # 3의 배수면 출력
        print(i)
    elif i%3==1: # 나머지가 1이면 10 더한 수 출력
        print(i+10)
    else:        # 나머지가 2이면 10 뺀 수 출력
        print(i-10)

0
11
-8
3
14


In [11]:
condition = True
if condition: # True 니까 출력
    print("You can pass")
else:
    print("You cannot pass")

You can pass


In [12]:
def three():
    return 3

def print_hello():
    print("Hello world")

print(three())
print_hello()

3
Hello world


In [13]:
def my_abs(val):
    if val<0:  # 음수면 -1 곱한 수 (절댓값) 반환
        return 0-val
    return val # 양수면 그냥 반환

print(my_abs(-7))

7


In [14]:
def print_abs(val):
    if val<0:
        print(0-val)
    else:
        print(val)

x = print_abs(-2.7) # print_abs를 호출하면 그냥 절댓값이 함수안에서 출력됨
print(x) # 반환된 값이 없으니 None이 나옴

2.7
None


In [15]:
def swap(val1, val2):
    tmp = val1
    val1 = val2
    val2 = tmp

x = 6
y = 3
swap(6,3)  # 함수 내부 지역변수끼리만 바꿈, 전역변수인 x, y에는 아무런 변경 없음
print(x,", ",y)

6 ,  3


# String Functions

In [16]:
word = 'Hello'
print(word.lower())
print(word.upper())
print('12'*2)
print('1'*2+'2'*3)
print('1'+'2')
print('Hi'+' there.')

hello
HELLO
1212
11222
12
Hi there.


In [17]:
s = '     Extras  \n'
print(s.strip())                # 양옆 공백문자 제거
s = '***10***'                  
print(s.strip('*'))
s = 'Let\'s split the words'
print(s.split(' '))
s = 'Jane,Doe,Cars,5'
print(s.split(','))

Extras
10
["Let's", 'split', 'the', 'words']
['Jane', 'Doe', 'Cars', '5']


In [18]:
word = 'Hello'
print(word[1:3])
print(word[4:7])
print(word[-4:-1])
print('HE' in word) # He여서 False임
print('He' in word) # 그래서 얜 True
print(word.find('el')) # 있어서 1 반환

el
o
ell
False
True
1


In [19]:
word = '1234'
print(int(word))
print(float(word))
word = 'Hi'
try:
    print(int(word))
except ValueError as e:
    print(e) # 문자열은 정수형으로 바뀔 수 없음

1234
1234.0
invalid literal for int() with base 10: 'Hi'


In [20]:
statement = 'We love {} {}.'
print(statement.format('data', 'analysis'))
statement = 'We love {0} {1}.'
print(statement.format('data', 'analysis'))
statement = 'We love {1} {0}.'
print(statement.format('analysis', 'data'))

We love data analysis.
We love data analysis.
We love data analysis.


In [21]:
msg = 'My name is ABC'
if 'name' in msg:
    print('name is in the msg variable')
else:
    print('name is not in the msg variable')

name is in the msg variable


In [22]:
txt = ' A string with spaces on either side '
ret1 = txt.lstrip()
ret2 = txt.rstrip()
ret3 = txt.strip()
print('<'+ret1+'>')
print('<'+ret2+'>')
print('<'+ret3+'>')

<A string with spaces on either side >
< A string with spaces on either side>
<A string with spaces on either side>


In [23]:
list = [11, 22, 33]
print(list)
print(list[1])
try:
    print(list[3])
except IndexError as e:
    print(e) # 인덱스 범위가 넘어감, max 2

for i in list:
    print(i)
    
for i in range(0, len(list)):
    print(list[i])

[11, 22, 33]
22
list index out of range
11
22
33
11
22
33


In [24]:
list[1] = 95
print(list[1]) # 변경된 값이 나옴

95


In [25]:
list.append(44)
list

[11, 95, 33, 44]

In [26]:
list = [11,22,33,44]
print(list.pop(2))
print(list)

33
[11, 22, 44]


In [27]:
list = [11,22,33,44]
list.remove(33)
print(list)

[11, 22, 44]


In [28]:
list = [1,2,3]
list2 = [4,5,6]
list.extend(list2) # list2의 각 요소들을 list의 요소로 추가함
print(list)

list = [1,2,3]
list2 = [4,5,6]
list.append(list2) # list2 자체를 list의 요소로 추가함
print(list)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]


In [29]:
list = [1,2,3]
list2 = [4,5,6]

for x,y in zip(list, list2):
    print(x,", ",y)

1 ,  4
2 ,  5
3 ,  6


In [30]:
strdata = 'Time is money!!'
listdata = [1,2,[1,2,3]]
print(strdata[5])
print(strdata[-2])
print(listdata[0])
print(listdata[-1])
print(listdata[2][-1])
print(strdata[1:5])
print(strdata[:7])
print(strdata[9:])
print(strdata[:-3])
print(strdata[-3:])
print(strdata[:])
print(strdata[::-2])

i
!
1
[1, 2, 3]
3
ime 
Time is
oney!!
Time is mone
y!!
Time is money!!
!ynms mT


# Tuple

In [31]:
tuple1 = ('Honda', 'Civic', 4, 2017)
print(tuple1)
print(tuple1[1])
print(len(tuple1))

('Honda', 'Civic', 4, 2017)
Civic
4


In [32]:
for i in tuple1:
    print(i)

Honda
Civic
4
2017


In [33]:
try:
    tuple1[3]=2018
except TypeError as e:
    print(e) # 튜플은 요소 변경 불가능

'tuple' object does not support item assignment


# Dictionary

In [34]:
dict = {('Ghostbusters', 2016):5.4,
        ('Ghostbusters', 1984):7.8}
dict[('Cars', 2006)] = 7.1
print(dict)
print(dict[('Ghostbusters', 2016)])
print(len(dict))

{('Ghostbusters', 2016): 5.4, ('Ghostbusters', 1984): 7.8, ('Cars', 2006): 7.1}
5.4
3


In [35]:
x = dict[('Cars', 2006)]
print(x)
x = dict.get(('Cars', 2006))
print(x)

7.1
7.1


In [36]:
dict.pop(('Ghostbusters', 2016))
print(dict)
del dict[('Cars', 2006)]
print(dict)

{('Ghostbusters', 1984): 7.8, ('Cars', 2006): 7.1}
{('Ghostbusters', 1984): 7.8}


In [37]:
dict = {('Ghostbusters', 2016):5.4,
        ('Ghostbusters', 1984):7.8,
        ('Cars', 2006):7.1}

for i in dict: # dict의 key값 출력
    print(i)

for i in dict: # key값의 인덱스의 값을 출력
    print(i[0], i[1])

for key,value in dict.items():
    print(key, ":", value)

('Ghostbusters', 2016)
('Ghostbusters', 1984)
('Cars', 2006)
Ghostbusters 2016
Ghostbusters 1984
Cars 2006
('Ghostbusters', 2016) : 5.4
('Ghostbusters', 1984) : 7.8
('Cars', 2006) : 7.1


# List and Dictionary Comprehension

In [38]:
list = [i**2 for i in range(1,11)]
print(list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [39]:
list = [i for i in range(6)]
print(list)

[0, 1, 2, 3, 4, 5]


In [40]:
dict = {i:i**2 for i in range(1,11)}
print(dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [41]:
dict = {i:chr(i) for i in range(65,91)}
print(dict)

{65: 'A', 66: 'B', 67: 'C', 68: 'D', 69: 'E', 70: 'F', 71: 'G', 72: 'H', 73: 'I', 74: 'J', 75: 'K', 76: 'L', 77: 'M', 78: 'N', 79: 'O', 80: 'P', 81: 'Q', 82: 'R', 83: 'S', 84: 'T', 85: 'U', 86: 'V', 87: 'W', 88: 'X', 89: 'Y', 90: 'Z'}


# Sets

In [42]:
colors = set(['blue','green','red'])
print(colors)
colors.add('yellow')
print(colors)
colors.add('blue') # 이미 있어서 추가 안됨, set은 요소가 중복되지 않음
print(colors)

{'red', 'green', 'blue'}
{'red', 'yellow', 'green', 'blue'}
{'red', 'yellow', 'green', 'blue'}


In [43]:
colors = set(['blue','green','red'])
print(colors)
colors.discard('green') # green 제거
print(colors)

{'red', 'green', 'blue'}
{'red', 'blue'}


In [44]:
colors_1 = set(['blue','green','red'])
colors_2 = set(['blue', 'yellow'])
print(colors_1.union(colors_2)) # 합집합 출력
print(colors_1.intersection(colors_2)) # 교집합 출력
print(colors_1|colors_2) # 합집합 출력
print(colors_1&colors_2) # 교집합 출력

{'red', 'yellow', 'green', 'blue'}
{'blue'}
{'red', 'yellow', 'green', 'blue'}
{'blue'}


# Numpy

In [45]:
import numpy as np
an_arr = np.array([3,33,333])
print(type(an_arr))
print(an_arr[0],an_arr[1],an_arr[2])

<class 'numpy.ndarray'>
3 33 333


In [47]:
another = np.array([[11,12,13],[21,22,23]])
print(another)
print(another.shape)


[[11 12 13]
 [21 22 23]]
(2, 3)


In [48]:
ex1 = np.zeros((2,2)) # 2*2의 0행렬 생성 / float로 만들어짐
print(ex1)
ex1 = np.full((2,2), 9.0) # 2*2의 9로 가득찬 행렬 생성 / float로 만들어짐
print(ex1)
ex1 = np.full((2,2), 9) # 2*2의 9로 가득찬 행렬 생성 / int로 만들어짐
print(ex1)

[[0. 0.]
 [0. 0.]]
[[9. 9.]
 [9. 9.]]
[[9 9]
 [9 9]]


In [53]:
ex2 = np.ones((1,2)) # 2*2의 1행렬 생성 / float로 만들어짐
print(ex2)
ex2 = np.random.random((2,2)) # 무작위 2*2 행렬 생성
print(ex2)
ex2 = np.eye(2,2) # 얘는 괄호 안에 2,2를 괄호로 안씌워 줘도 된다
print(ex2)        # 대각선으로 1인 행렬 / float로 만들어짐

[[1. 1.]]
[[0.31392139 0.91998953]
 [0.83148295 0.76516833]]
[[1. 0.]
 [0. 1.]]


In [51]:
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
row_rank1 = an_array[1,:]
print(row_rank1, row_rank1.shape)
row_rank2 = an_array[:2, 1:3]
print(row_rank2, row_rank2.shape)
row_rank3 = an_array[1:2, :]
print(row_rank3, row_rank3.shape)

[21 22 23 24] (4,)
[[12 13]
 [22 23]] (2, 2)
[[21 22 23 24]] (1, 4)


In [52]:
col_rank1 = an_array[:,1]
print(col_rank1, col_rank1.shape)
col_rank2 = an_array[:,1:2]
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)


In [55]:
col_indices = np.array([0,1,2,0])
print(col_indices)
row_indices = np.arange(4) # 0~3까지 4개의 수를 요소로 같는 행렬 생성
print(row_indices)

[0 1 2 0]
[0 1 2 3]


In [59]:
for row, col in zip(row_indices, col_indices):
    print(row, ', ', col)

an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34],
                     [41,42,43,44]])

print(an_array[row_indices, col_indices])
an_array[row_indices, col_indices] += 10000
print(an_array)
# 위와 같은 연산은 오직 numpy array에서만 가능, list는 불가능

0 ,  0
1 ,  1
2 ,  2
3 ,  0
[11 22 33 41]
[[10011    12    13    14]
 [   21 10022    23    24]
 [   31    32 10033    34]
 [10041    42    43    44]]


In [61]:
an_array = np.array([[11,12],[21,22],[31,32]])

filter = an_array>15
print(filter)
print(an_array[filter])
print(an_array[an_array%2==0])

[[False False]
 [ True  True]
 [ True  True]]
[21 22 31 32]
[12 22 32]


In [62]:
an_array[an_array%2==0] += 100 # 짝수인 요소에 100 더함
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [65]:
ex1 = np.array([11,12])
print(ex1.dtype)
ex2 = np.array([11.0, 12.0]) # 출력시 .0은 .으로 생략됨
print(ex2.dtype)
ex3 = np.array([11,21], dtype=np.int64)
print(ex3.dtype)
ex4 = np.array([11.1, 12.7], dtype=np.int64) # 내림됨
print(ex4.dtype)
print(ex4)
ex5 = np.array([11,21], dtype=np.float64)
print(ex5.dtype)
print(ex5)

int32
float64
int64
int64
[11 12]
float64
[11. 21.]


In [66]:
x = np.array([[111,112],[121,122]], dtype=np.int32)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [68]:
print(x+y)
print()
print(np.add(x,y)) # 두 행렬 더하기

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [67]:
print(x-y)
print()
print(np.subtract(x,y)) # 두 행렬 빼기

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [69]:
print(x*y)
print()
print(np.multiply(x,y)) # 두 행렬 곱셉, 행렬곱이 아니라 그냥 각 요소끼리 곱셈

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [70]:
print(x/y)
print()
print(np.divide(x,y)) # 두 행렬 나눗셈, 행렬 나눗셈이 아니라 각 요소끼리 나눗셈

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [72]:
print(np.sqrt(x)) # x의 각 요소들을 루트 씌운 행렬
print(np.exp(x)) # x의 각 요소들을 e의 승으로 만든 행렬

[[10.53565375 10.58300524]
 [11.         11.04536102]]
[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [73]:
arr = 10*np.random.randn(2,5) # 무작위의 2*5 행렬 생성
print(arr)
print(arr.mean()) # 모든 요소의 평균 출력
print(arr.mean(axis=1)) # 행의 평균 출력
print(arr.mean(axis=0)) # 열의 평균 출력
print(arr.sum()) # 모든 요소의 합
print(np.median(arr, axis=1)) # 각 행의 중앙값 출력

[[ 5.00633303 -4.0471895  -3.47848896 -9.52086727  7.32393165]
 [ 8.33374757 11.80420606  0.64967412  0.55002738  6.2996592 ]]
2.2921033270994458
[-0.94325621  5.52746286]
[ 6.6700403   3.87850828 -1.41440742 -4.48541994  6.81179542]
22.921033270994457
[-3.47848896  6.2996592 ]


In [74]:
unsorted = np.random.randn(10)
print(unsorted)
print(type(unsorted))

sorted = np.sort(unsorted)
print(unsorted)
print(sorted)
sorted_descending = np.sort(unsorted)[::-1]
print(sorted_descending)

[ 1.38645343  0.29497218  0.01938473  2.23485011  0.10146512 -1.10630732
 -0.73274278  0.4393095  -0.31861667 -0.20512866]
<class 'numpy.ndarray'>
[ 1.38645343  0.29497218  0.01938473  2.23485011  0.10146512 -1.10630732
 -0.73274278  0.4393095  -0.31861667 -0.20512866]
[-1.10630732 -0.73274278 -0.31861667 -0.20512866  0.01938473  0.10146512
  0.29497218  0.4393095   1.38645343  2.23485011]
[ 2.23485011  1.38645343  0.4393095   0.29497218  0.10146512  0.01938473
 -0.20512866 -0.31861667 -0.73274278 -1.10630732]


In [75]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array)) # 각각 보여줌 (겹치는게 두번 X)

[1 2 4]


In [76]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1,s2)
print(np.intersect1d(s1,s2)) # 1차원 배열 교집합
print(np.union1d(s1,s2)) # 1차원 배열 합집합
print(np.setdiff1d(s1,s2)) # s1엔 있는데 s2엔 없는거 출력 (차집합)
print(np.in1d(s1,s2)) # s1에 있는게 s2에 있는지 Boolean을 반환해줌

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']
['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [78]:
start = np.zeros((4,3))
print(start)
add_rows = np.array([1,0,2])
print(add_rows)
y = start+add_rows # start의 각 행마다 add_rows의 값을 더함
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 0 2]
[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [79]:
add_cols = np.array([[0,1,2,3]])
print(add_cols.shape)
print(add_cols)
add_cols_T = add_cols.T # 행을 열로 변환

print(add_cols_T)
print(add_cols_T.shape)

y = start+add_cols_T # 각 열마다 더함
print(y)

(1, 4)
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]
(4, 1)
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [80]:
add_scalar = np.array([1])
print(start+add_scalar) # 다 1씩 더해짐

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)
arrB = [0,1,0,2]
print(arrB)
print(arrA+arrB) # arrA의 각 행에 arrB를 더해줌

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0, 1, 0, 2]
[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [82]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[3,3]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[5 5]
 [5 5]]

[[5 5]
 [5 5]]


In [83]:
a1d = np.array([9,9])
b1d = np.array([10,10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [84]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


In [85]:
A = np.arange(2*3*4).reshape([2,3,4])
B = np.arange(2*3*4).reshape([2,4,3])-1
print('A')
print(A)
print('B')
print(B)
print('A@B')
print(A@B) # 내적

A
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B
[[[-1  0  1]
  [ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]
  [20 21 22]]]
A@B
[[[  36   42   48]
  [  92  114  136]
  [ 148  186  224]]

 [[ 852  906  960]
  [1100 1170 1240]
  [1348 1434 1520]]]


In [87]:
A = np.arange(2*3*4).reshape([2,3,4])
B = np.arange(2*3*4).reshape([2,4,3])-1
print('A')
print(A)
print('B')
print(B)
print('A.dot(B)')
print(A.dot(B))

A
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B
[[[-1  0  1]
  [ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]
  [20 21 22]]]
A.dot(B)
[[[[  36   42   48]
   [ 108  114  120]]

  [[  92  114  136]
   [ 356  378  400]]

  [[ 148  186  224]
   [ 604  642  680]]]


 [[[ 204  258  312]
   [ 852  906  960]]

  [[ 260  330  400]
   [1100 1170 1240]]

  [[ 316  402  488]
   [1348 1434 1520]]]]


In [88]:
ex1 = np.array([[11,12],[21,22]])
print(ex1)

print(np.sum(ex1))

[[11 12]
 [21 22]]
66


In [90]:
print(np.sum(ex1, axis=0))
print(np.sum(ex1, axis=1))

[32 34]
[23 43]


In [91]:
x = np.random.randn(8)
print(x)
y = np.random.randn(8)
print(y)
np.maximum(x,y) # 두 행렬에서 더 큰 요소끼리만 합친거

[ 1.47583203 -2.05210935  0.61884595 -1.27375197  1.13177698 -0.7539462
  1.39881922  1.17219247]
[ 0.77874368 -0.45654157 -0.00821621  0.57630225 -1.06940425  1.54143238
  0.22179901 -0.97862801]


array([ 1.47583203, -0.45654157,  0.61884595,  0.57630225,  1.13177698,
        1.54143238,  1.39881922,  1.17219247])

## Transpose

In [92]:
ex1 = np.array([[11,12], [21,22]])
print(ex1.T) # Transpose, 행을 열로, 열을 행으로

[[11 21]
 [12 22]]


## Indexing using where()

In [93]:
x_1 = np.array([1,2,3,4,5])
y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])
out = np.where(filter, x_1, y_1) # True면 x_1을, False면 y_1를 반환
print(out)

[ 1 22  3 44  5]


In [94]:
mat = np.random.rand(5,5)
print(mat)
print(np.where(mat>0.5, 1000, -1)) # 조건 만족시 1000, 아닐시 -1

[[0.4235735  0.74040468 0.55791785 0.69782823 0.01310826]
 [0.87413641 0.69938164 0.90190293 0.95287852 0.95090886]
 [0.30218983 0.78525656 0.73993246 0.26127377 0.84445869]
 [0.90049876 0.88147341 0.87013486 0.82782638 0.92694922]
 [0.94873974 0.74115098 0.37689654 0.04333016 0.48041727]]
[[  -1 1000 1000 1000   -1]
 [1000 1000 1000 1000 1000]
 [  -1 1000 1000   -1 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000   -1   -1   -1]]


## "any" or "all" conditionals

In [95]:
arr_bools = np.array([True, False, True, True, False])
print(arr_bools.any()) # 하나라도 맞으면 True
print(arr_bools.all()) # 하나라도 틀리면 False

True
False


## Random Number Generation

In [96]:
Y = np.random.normal(size=(1,5))
print(Y)
print(np.random.normal(size=(1,5))[0])

[[-0.65835425 -0.32338464  0.83288234 -0.28664291  0.20910049]]
[-0.52562801  0.85945088  0.77267887  0.82159124 -1.59095171]


In [97]:
Z = np.random.randint(low=2, high=100, size=10)
print(Z)
print(np.random.permutation(Z))

[65 91 24 37 56 95 36 72 80  5]
[37 65 72 56 36 80  5 91 95 24]


## Merging data sets

In [98]:
K = np.random.randint(low=2, high=50,size=(2,2))
print(K)
print()

M = np.random.randint(low=2, high=50, size=(2,2))
print(M)

[[27 21]
 [29 21]]

[[10 22]
 [ 2 13]]


In [99]:
print(np.vstack((K,M))) # 수직으로 쌓기
print(np.hstack((K,M))) # 수평으로 쌓기
print(np.concatenate([K,M], axis=0)) # 수직으로 쌓기 (column)
print(np.concatenate([K,M], axis=1)) # 수평으로 쌓기 (row)

[[27 21]
 [29 21]
 [10 22]
 [ 2 13]]
[[27 21 10 22]
 [29 21  2 13]]
[[27 21]
 [29 21]
 [10 22]
 [ 2 13]]
[[27 21 10 22]
 [29 21  2 13]]
